version: 0.0
os: linux
files:
  - source: webapp/NoteTaking/target/ROOT.war
    destination: /opt/tomcat/latest/webapps
  - source: appspec.yml
    destination: /home/centos
  - source: applicationStart.sh
    destination: /home/centos
  - source: afterInstall.sh
    destination: /home/centos
  - source: applicationStop.sh
    destination: /home/centos
  - source: beforeInstall.sh
    destination: /home/centos
hooks:
  ApplicationStart:
    - location: applicationStart.sh
      timeout: 180
      runas: root
  AfterInstall:
   - location: afterInstall.sh
     timeout: 300
     runas: tomcat
  BeforeInstall:
    - location: beforeInstall.sh
      timeout: 300
      runas: tomcat
  ApplicationStop:
    - location: applicationStop.sh
      timeout: 300
      runas: root